# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27ea83859f490e2688bc2cc9727a593237a2c52917c6382d7f020c92b070a4bcacebfd2d6ae207e95aad0e8126593ea641619eeb888f2e9de6ba03a5109db193

test:
  secret_key_base: 61d99b1d0f82cbe85267d39bb9e1a1ab7591b552e94132954e12995b543c457127eec959b04368edaab2ed54345d18e22ee54df1cd47d84eac762c7bf1f88f60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
